/**
 * Registro canónico de las 123 reglas V-* de opm-visual-es.md.
 *
 * PROPÓSITO ARQUITECTURAL
 * -----------------------
 * El `VisualRenderSpec` es el contrato entre la fase semántica (kernel-to-visual-render-spec)
 * y la fase de renderizado (JointJS adapter + iso-19450). Este registro hace explícito en
 * qué fase vive cada regla y cuál es su estado de implementación.
 *
 * Toda regla nueva detectada en la SSOT debe registrarse aquí ANTES de implementarse.
 * El pipeline es:
 *
 *   SemanticKernel
 *     ↓ [spec-compiler]          ← reglas semánticas → atributos de VisualRenderSpec
 *   VisualRenderSpec
 *     ↓ [verifier]               ← reglas de validación → VisualRenderVerificationIssue
 *     ↓ [renderer / style-pack]  ← reglas visuales → JointJS attrs / iso-19450
 *   JointJS Graph
 *
 * FLUJO PARA NUEVA REGLA
 * ----------------------
 * 1. Agregar entrada aquí con status: "deferred".
 * 2. Decidir `stage`: spec-compiler | verifier | renderer | style-pack | not-applicable | simulation-only.
 * 3. Implementar en el módulo indicado por `implementedIn`.
 * 4. Cambiar status a "implemented" o "partial".
 */

export type VisualRuleStatus =
  | "implemented"     // implementada completamente en opmodel
  | "partial"         // implementada parcialmente, ver note
  | "deferred"        // reconocida, pendiente de implementación
  | "not-applicable"  // norma semántica sin impacto visual directo
  | "simulation-only" // solo aplica durante simulación activa (§17)
  | "eliminated";     // regla eliminada/absorbida por otra (ej. V-48 → V-4)

export type VisualRuleStage =
  | "spec-compiler"  // kernel-to-visual-render-spec.ts — convierte kernel → VisualRenderSpec
  | "verifier"       // visual-render-verifier.ts — valida VisualRenderSpec
  | "renderer"       // visual-render-spec-to-joint-graph.ts — convierte spec → JointJS
  | "style-pack"     // iso-19450.ts — decisiones cosméticas (colores, dimensiones, tipografía)
  | "layout"         // opm-layout.ts — posicionamiento y flujo temporal
  | "not-applicable"
  | "simulation-only";

export interface VisualRuleEntry {
  code: string;
  section: string;
  summary: string;
  stage: VisualRuleStage;
  status: VisualRuleStatus;
  implementedIn?: string;
  verifierCode?: string;  // código VR-XXX si tiene check en verifier
  note?: string;
}

export const VISUAL_RULES_REGISTRY: VisualRuleEntry[] = [
  // ─── §1 Shapes de Things ────────────────────────────────────────────────
  {
    code: "V-1",
    section: "§1.3",
    summary: "Defaults: informational (no shadow), systemic (solid border).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → affiliation + essence fields",
  },
  {
    code: "V-2",
    section: "§1.3",
    summary: "Perseverance is not visual — inferred from type.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-3",
    section: "§1.5",
    summary: "Triangle vertex points toward refinable; base toward refiners.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "procedural-link.ts → triangle-filled / triangle-hollow markers",
  },
  {
    code: "V-4",
    section: "§2",
    summary: "States must not exist outside their owner object (no floating states).",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-007",
    verifierCode: "VR-007",
  },
  {
    code: "V-5",
    section: "§3",
    summary: "Stateless object can only be created (result) or destroyed (consumption).",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-016",
    verifierCode: "VR-016",
  },
  {
    code: "V-6",
    section: "§2.2",
    summary: "State designations: initial=thick border, final=double border, default=diagonal arrow.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "state-shape.ts → createStateShape (FinalStateElement, stateInitial strokeWidth, defaultArrow)",
  },
  {
    code: "V-7",
    section: "§3.1",
    summary: "Effect link requires object with at least one state.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-010",
    verifierCode: "VR-010",
  },
  {
    code: "V-8",
    section: "§3.1",
    summary: "Result link to stateful object must connect to object rectangle, not directly to initial state.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-011",
    verifierCode: "VR-011",
  },
  {
    code: "V-9",
    section: "§3.1",
    summary: "Effect-entry-only without specified exit → defaults to default state or probability distribution.",
    stage: "spec-compiler",
    status: "deferred",
    note: "Requires inference from kernel state graph when exit state is unspecified.",
  },
  {
    code: "V-10",
    section: "§3.2",
    summary: "If enabler disappears during execution, process stops; affected state becomes indeterminate.",
    stage: "simulation-only",
    status: "simulation-only",
  },
  {
    code: "V-11",
    section: "§3.1",
    summary: "A thing is either transformed OR enabler for a given link, never both.",
    stage: "verifier",
    status: "deferred",
    note: "Requires per-link role validation in the kernel before spec compilation.",
  },
  {
    code: "V-12",
    section: "§3.2",
    summary: "Event link is the segment from object/state TO process (not the reverse segment).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → edge direction preserved from kernel link direction",
  },
  {
    code: "V-13",
    section: "§3.2",
    summary: "Event is consumed after evaluation, even if precondition fails.",
    stage: "simulation-only",
    status: "simulation-only",
  },
  {
    code: "V-14",
    section: "§5.1",
    summary: "AND is the default fan operator; no explicit arc marker needed.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "fan-shape.ts → AND fans skipped (no badge rendered)",
  },
  {
    code: "V-15",
    section: "§5.1",
    summary: "XOR and OR apply to all procedural link families.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → fan.operator propagated from kernel",
  },
  {
    code: "V-16",
    section: "§5.1",
    summary: "Fan arc placed at convergent end (shared endpoint of all member links).",
    stage: "renderer",
    status: "partial",
    implementedIn: "visual-render-spec-to-joint-graph.ts → badge positioned at commonNodeId",
    note: "Badge approximates arc position. Geometric arc requires post-routing. Deferred.",
  },
  {
    code: "V-17",
    section: "§5.1",
    summary: "Fan can be converging (many→one) or diverging (one→many).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → fan.direction propagated",
  },
  {
    code: "V-18",
    section: "§5.8",
    summary: "Probabilistic fan is always XOR. Each member link annotated with Pr=p, sum=1.0.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "fan-shape.ts → isProbabilistic badge prefix 'Pr:', edge.probability in VisualRenderEdge",
  },
  {
    code: "V-19",
    section: "§5.8",
    summary: "Simple result to stateful object is semantically equivalent to XOR fan of result-with-state links.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Derived equivalence rule, no visual treatment needed beyond V-15.",
  },
  {
    code: "V-20",
    section: "§6",
    summary: "Path trajectories: entry path label must match exit path label for activation.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "procedural-link.ts → pathLabel appended as italic label at position 0.6",
  },
  {
    code: "V-21",
    section: "§6",
    summary: "Multiplicity parameter names must be unique across the model.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Model-level validation, not a rendering concern.",
  },
  {
    code: "V-22",
    section: "§7",
    summary: "Multiplicity placed near the link endpoint or near the refiners in structural links.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "procedural-link.ts → multiplicitySource at 0.1, multiplicityTarget at 0.9",
  },
  {
    code: "V-23",
    section: "§7",
    summary: "Multiplicity applies to tagged, aggregation-participation, and procedural links.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → multiplicitySource/multiplicityTarget propagated",
  },
  {
    code: "V-24",
    section: "§8",
    summary: "Refinable and refiners must have the same perseverance (both objects or both processes).",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-017 (aggregation/generalization/classification cross-kind check)",
    verifierCode: "VR-017",
  },
  {
    code: "V-25",
    section: "§8",
    summary: "Exhibition-characterization is the only structural link that can cross object/process.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-017 (exhibition exempt from cross-kind restriction)",
    verifierCode: "VR-017",
  },
  {
    code: "V-26",
    section: "§8",
    summary: "Four exhibitor-feature combinations are valid (object↔attribute, object↔operation, process↔attribute, process↔operation).",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-27",
    section: "§8.3",
    summary: "Classification-instantiation doesn't distinguish complete vs. incomplete collections.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-28",
    section: "§8.4",
    summary: "Multiple inheritance is allowed.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-29",
    section: "§8.4",
    summary: "Discriminant attribute restricts valid values per specialization.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-30",
    section: "§8.5",
    summary: "Bidirectional and reciprocal variants do NOT exist for state-only destinations.",
    stage: "verifier",
    status: "deferred",
    note: "Requires checking that bidirectional edges don't target states.",
  },
  {
    code: "V-31",
    section: "§10.1",
    summary: "Vertical position determines sequential invocation order in process decomposition.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts → subprocesses stacked vertically (top→bottom)",
  },
  {
    code: "V-32",
    section: "§10.1",
    summary: "Same vertical level = parallel execution; last to finish triggers next level.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts → parallel subprocesses at same Y",
  },
  {
    code: "V-33",
    section: "§10.2",
    summary: "Refinable appears with thick border in both parent and child OPD.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "object-shape.ts / process-shape.ts → isRefined → strokeWidth refined",
  },
  {
    code: "V-34",
    section: "§10.3",
    summary: "Refined process ellipse enlarges to contain subprocesses.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → inZoomContainerOf → parent.embed(child)",
  },
  {
    code: "V-35",
    section: "§10.3",
    summary: "Time flows top-to-bottom; vertical position of subprocesses determines execution order.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts → subprocess Y incremented sequentially",
  },
  {
    code: "V-36",
    section: "§11",
    summary: "Links to outer refined process boundary distribute to all subprocesses.",
    stage: "spec-compiler",
    status: "deferred",
    note: "Requires distributing incoming agent/instrument links across all subprocess nodes in the child OPD.",
  },
  {
    code: "V-37",
    section: "§11.2",
    summary: "Consumption/result must NOT connect to outer boundary of refined process.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-012",
    verifierCode: "VR-012",
  },
  {
    code: "V-38",
    section: "§11.3",
    summary: "Event links from systemic objects must not cross in-zoom decomposition boundary.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-013",
    verifierCode: "VR-013",
  },
  {
    code: "V-39",
    section: "§11.3",
    summary: "If condition causes subprocess skip, control passes to next subprocess.",
    stage: "simulation-only",
    status: "simulation-only",
  },
  {
    code: "V-40",
    section: "§11.4",
    summary: "Effect link is split in decomposition: two half-links (entry + exit) with scission marker.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → isSplit+splitRole on crossing edges; procedural-link.ts → dash pattern + glyph",
  },
  {
    code: "V-41",
    section: "§11.4",
    summary: "Split links cannot have control modifiers (event/condition).",
    stage: "verifier",
    status: "partial",
    note: "Split detected and marked; modifier restriction not yet enforced in verifier.",
  },
  {
    code: "V-42",
    section: "§11.4",
    summary: "Object can be instrument at abstract level and affected at detail level (role change).",
    stage: "verifier",
    status: "deferred",
    note: "Requires cross-OPD consistency check between instrument and effect roles.",
  },
  {
    code: "V-43",
    section: "§12",
    summary: "Result+consumption on the same object is invalid (use effect instead).",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-014",
    verifierCode: "VR-014",
  },
  {
    code: "V-44",
    section: "§12",
    summary: "Transforming link always prevails over enabling link in recomposition.",
    stage: "verifier",
    status: "partial",
    note: "Semantic precedence rule; routing priority set in spec-compiler. Full validation deferred.",
  },
  {
    code: "V-45",
    section: "§13.1",
    summary: "Duration values shown inside process ellipse under name and time unit.",
    stage: "renderer",
    status: "partial",
    implementedIn: "process-shape.ts → formatDuration + displayText; kernel-to-visual-render-spec.ts → duration propagation",
    note: "Spec propagation and single-line rendering implemented. Distribution-only and complex notation deferred.",
  },
  {
    code: "V-46",
    section: "§13.2",
    summary: "SD contains exactly one systemic process.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-018",
    verifierCode: "VR-018",
  },
  {
    code: "V-47",
    section: "§14.1",
    summary: "Nominal uniqueness evaluated at model level; every appearance must render unambiguously.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-48",
    section: "§2",
    summary: "ELIMINATED — content absorbed by V-4.",
    stage: "not-applicable",
    status: "eliminated",
  },
  {
    code: "V-49",
    section: "§3",
    summary: "Consumed object disappears at the START of the process, not the end.",
    stage: "simulation-only",
    status: "simulation-only",
  },
  {
    code: "V-50",
    section: "§16.2",
    summary: "Legibility: ≤20-25 things per OPD context.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-019",
    verifierCode: "VR-019",
  },
  {
    code: "V-51",
    section: "§16.2",
    summary: "No occlusion between things; links must not traverse occupied areas; minimize crossings.",
    stage: "layout",
    status: "partial",
    implementedIn: "opm-layout.ts → column-based layout minimizes crossings",
    note: "Algorithmic crossing minimization not implemented; layout heuristics applied.",
  },
  {
    code: "V-52",
    section: "§14.2",
    summary: "Any model element can appear in any number of OPDs.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → per-OPD slice compilation",
  },
  {
    code: "V-53",
    section: "§17.1",
    summary: "Executing process shown with fully filled (shaded) ellipse.",
    stage: "simulation-only",
    status: "simulation-only",
  },
  {
    code: "V-54",
    section: "§17.2",
    summary: "Current state highlighted (thicker border or differential color) vs. inactive states.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → state.current → fill #dbeafe",
  },
  {
    code: "V-55",
    section: "§10.3",
    summary: "Time flows top-to-bottom within process decomposition.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts (same as V-35)",
  },
  {
    code: "V-56",
    section: "§8.5",
    summary: "Bidirectional link with identical labels = reciprocal; harpoon markers on both ends.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "procedural-link.ts → bidirectional → harpoon targetMarker + sourceMarker",
  },
  {
    code: "V-57",
    section: "§8.1",
    summary: "Aggregation parts can be independently transformed without transforming the whole.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-58",
    section: "§8.3",
    summary: "Class shows attribute ranges; instance shows concrete values; instance named as 'Instance : Class'.",
    stage: "renderer",
    status: "partial",
    note: "Label format not enforced. VisualRenderNode carries label as-is from kernel.",
  },
  {
    code: "V-59",
    section: "§10.1",
    summary: "Async subprocesses activated by independent events compete without sequential order.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Semantic rule, layout handles independently activated subprocesses by event links.",
  },
  {
    code: "V-60",
    section: "§15.1",
    summary: "OPD is composed of OPD constructors (≥2 things + ≥1 link).",
    stage: "verifier",
    status: "partial",
    implementedIn: "visual-render-verifier.ts → VR-001 (≥1 node), VR-004 (edge refs)",
    note: "Minimum 2 things + 1 link not strictly enforced as a unit.",
  },
  {
    code: "V-61",
    section: "§15.1",
    summary: "Link has origin, destination, and connector (line + symbol + optional labels).",
    stage: "renderer",
    status: "implemented",
    implementedIn: "procedural-link.ts → source/target IDs + targetMarker + labels",
  },
  {
    code: "V-62",
    section: "§10.3",
    summary: "In-zooming proceeds in two phases: Show Content + Refine Links.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → two-pass OPD slice compilation",
  },
  {
    code: "V-63",
    section: "§1.1b",
    summary: "Colors are informative, not normative. Green/blue scheme is reference.",
    stage: "style-pack",
    status: "implemented",
    implementedIn: "iso-19450.ts → palette (thingFillObject #eef3fb, thingFillProcess #e8f7ee, strokes)",
  },
  {
    code: "V-64",
    section: "§15.2",
    summary: "OPM Model = OPD Set + OPL Spec; specifies a System.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-65",
    section: "§15.2",
    summary: "Every OPD has an OPL counterpart; duality is bidirectional.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → canonicalOpl included in VisualRenderSpec",
  },
  {
    code: "V-66",
    section: "§15.3",
    summary: "Conectar process: takes disconnected things + links → connected things.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-67",
    section: "§18.4",
    summary: "Every object has a set of states (s=0 = stateless; s≥1 = stateful).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → states[] built from kernel.states",
  },
  {
    code: "V-68",
    section: "§18.5",
    summary: "State-specific object named as 'StateLabel ObjectName' (e.g. 'Designed Product').",
    stage: "not-applicable",
    status: "not-applicable",
    note: "OPL naming convention, not a visual rendering concern.",
  },
  {
    code: "V-69",
    section: "§10.2",
    summary: "Thick border on refinable in both in-zooming and unfolding to new OPD.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "object-shape.ts + process-shape.ts → isRefined → stroke.refined",
  },
  {
    code: "V-70",
    section: "§10.2",
    summary: "Intradiagram unfolding does NOT produce thick border (refinable and refiners share OPD).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → isRefined only set for inter-OPD refinements",
  },
  {
    code: "V-71",
    section: "§1.2",
    summary: "Contour type (solid/dashed) persists across all refinement levels.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → affiliation propagated per thing, persistent in child OPDs",
  },
  {
    code: "V-72",
    section: "§8.4",
    summary: "Inheritance applies through refinement by unfolding.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-73",
    section: "§8.4",
    summary: "Inherited links are NOT explicitly drawn; effect inferred from generalization tree.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → only explicit links in spec.edges are rendered",
  },
  {
    code: "V-74",
    section: "§8.4",
    summary: "Affiliation inheritance: attributes of environmental objects are automatically environmental.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → affiliation from kernel.things",
  },
  {
    code: "V-75",
    section: "§8.4",
    summary: "Overriding: specialization can replace inherited participant with a different specialization.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-76",
    section: "§8.4",
    summary: "Common link migration: shared links across specializations move to the general.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-77",
    section: "§10.3",
    summary: "Implicit invocation by vertical position only applies to process decomposition.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts → in-zoom layout for processes, different for objects",
  },
  {
    code: "V-78",
    section: "§10.3",
    summary: "Object decomposition: spatial position encodes semantic arrangement, not temporal order.",
    stage: "layout",
    status: "implemented",
    implementedIn: "opm-layout.ts → object in-zoom uses grid layout, not vertical timeline",
  },
  {
    code: "V-79",
    section: "§10.3",
    summary: "In child OPD, refined thing appears as CONTAINER (enlarged); connected things as EXTERNAL.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → inZoomContainerOf → embed relationship",
  },
  {
    code: "V-80",
    section: "§10.3",
    summary: "Things connected to refinable in parent OPD are copied as external elements in child OPD.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → visibleThingIds from slice",
  },
  {
    code: "V-81",
    section: "§10.4",
    summary: "ALL things connected via any link to refinable (with appearance in parent OPD) are copied.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → full slice visibleThings",
  },
  {
    code: "V-82",
    section: "§10.4",
    summary: "Unfolding copies only direct structural children (aggregation/exhibition destinations).",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → unfold slice restricted to structural children",
  },
  {
    code: "V-83",
    section: "§10.4",
    summary: "External elements (internal=false) cannot be refined within their own child OPD.",
    stage: "verifier",
    status: "partial",
    implementedIn: "visual-render-verifier.ts → VR-020 (warning level)",
    verifierCode: "VR-020",
    note: "`isRefined` in the spec signals existence of any refinement in the atlas, not refinement within the current child OPD. VR-020 emits a warning until the spec exposes per-appearance refinement scope.",
  },
  {
    code: "V-84",
    section: "§10.4",
    summary: "Internal objects cascade-deleted when refined thing is deleted.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Model mutation concern, not a rendering concern.",
  },
  {
    code: "V-85",
    section: "§10.4",
    summary: "External objects exist independently of refinement.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-86",
    section: "§10.6",
    summary: "State s of T is suppressed in parent OPD when child OPD references s via links.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → suppressed state entries added to states[]",
  },
  {
    code: "V-87",
    section: "§10.6",
    summary: "State suppression only applies to decomposition, not unfolding.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → suppression guarded by containerRef (in-zoom only)",
  },
  {
    code: "V-88",
    section: "§10.6",
    summary: "States NOT referenced in links to refinable are NOT suppressed.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → suppression only when visibleOwnStates.length > 0",
  },
  {
    code: "V-89",
    section: "§10.6",
    summary: "Multiple child OPDs: suppressed states = union across all child OPDs.",
    stage: "spec-compiler",
    status: "partial",
    note: "Single child OPD suppression implemented. Multi-child union not yet computed.",
  },
  {
    code: "V-90",
    section: "§10.6",
    summary: "Suppressed states in parent OPD are revealed in child OPD linked to subprocesses.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → child OPD shows states from visibleStateIds",
  },
  {
    code: "V-91",
    section: "§10.5",
    summary: "Structural links to container ARE visible in child OPD.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → structural links included in child OPD edges",
  },
  {
    code: "V-92",
    section: "§10.5",
    summary: "Procedural links to container are NOT directly visible in child OPD.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → procedural links to container excluded from child OPD",
  },
  {
    code: "V-93",
    section: "§10.5",
    summary: "Links between internal elements of child OPD are visible normally.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → all intra-internal edges included",
  },
  {
    code: "V-94",
    section: "§10.5",
    summary: "Links that touch neither container nor internals are invisible in child OPD.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → edges filtered by visibleThingIds",
  },
  {
    code: "V-95",
    section: "§10.6",
    summary: "Essence (physical/informational) does not change through refinement.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → essence from kernel.things (static property)",
  },
  {
    code: "V-96",
    section: "§10.6",
    summary: "Perseverance (static/dynamic) does not change through refinement.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-97",
    section: "§10.6",
    summary: "Names do not change through refinement.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-98",
    section: "§14.2",
    summary: "Facts asserted in one OPD cannot contradict facts in another OPD.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Cross-OPD semantic validation, not a rendering concern.",
  },
  {
    code: "V-99",
    section: "§14.2",
    summary: "Importance proportional to highest OPD level where thing appears.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → importance field (1=main-process, 2=process, 3=object)",
  },
  {
    code: "V-100",
    section: "§14.3",
    summary: "A thing cannot refine itself transitively (no cycles in refinement hierarchy).",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Kernel-level invariant enforced before spec compilation.",
  },
  {
    code: "V-101",
    section: "§14.4",
    summary: "Visual instance ≠ logical instance. Same entity, different view.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-102",
    section: "§14.4",
    summary: "Cross-type visual instances invalid (object cannot be visual instance of process).",
    stage: "verifier",
    status: "deferred",
  },
  {
    code: "V-103",
    section: "§11.2",
    summary: "Consumption/input distributed to first subprocess (min Y); result/output to last (max Y).",
    stage: "spec-compiler",
    status: "partial",
    note: "Distribution logic depends on post-layout Y positions. Layout computes this but spec-compiler doesn't use it yet.",
  },
  {
    code: "V-104",
    section: "§11.2",
    summary: "Agent/instrument links distributed to ALL subprocesses.",
    stage: "spec-compiler",
    status: "deferred",
    note: "Requires fan-expansion of agent/instrument in child OPD spec.",
  },
  {
    code: "V-105",
    section: "§11.2",
    summary: "Structural links are NOT distributed — they remain on the container.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → structural links kept on container node",
  },
  {
    code: "V-106",
    section: "§11.2",
    summary: "If no subprocesses exist yet, link connects to container directly (temporary).",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → link renders to container when no subprocess targets",
  },
  {
    code: "V-107",
    section: "§11.2",
    summary: "Link distribution only applies to decomposition, not unfolding.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → distribution guarded by in-zoom refinement type",
  },
  {
    code: "V-108",
    section: "§11.3",
    summary: "Event links from ENVIRONMENTAL objects CAN cross in-zoom boundary with explicit contingency.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-013 only flags systemic (affiliation=systemic) nodes",
    verifierCode: "VR-013",
  },
  {
    code: "V-109",
    section: "§11.3",
    summary: "Boundary restrictions (V-37, V-38, V-39) only apply to decomposition, not unfolding.",
    stage: "verifier",
    status: "implemented",
    implementedIn: "visual-render-verifier.ts → VR-012/VR-013 guarded by isChildOpd check",
  },
  {
    code: "V-110",
    section: "§11.4",
    summary: "Scission is the ONLY mechanism to resolve effect entry-exit underspecification in decomposition.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → isSplit marks crossing edges",
  },
  {
    code: "V-111",
    section: "§11.5",
    summary: "Role-change object shows intermediate states in child OPD not visible in parent.",
    stage: "spec-compiler",
    status: "deferred",
    note: "Requires cross-level role tracking in kernel. Deferred.",
  },
  {
    code: "V-112",
    section: "§11.5",
    summary: "Role-change only applies to decomposition.",
    stage: "spec-compiler",
    status: "deferred",
    note: "Follows from V-111.",
  },
  {
    code: "V-113",
    section: "§14.3",
    summary: "Only leaf OPDs are deletable.",
    stage: "not-applicable",
    status: "not-applicable",
    note: "Model mutation concern.",
  },
  {
    code: "V-114",
    section: "§14.5",
    summary: "View OPDs are ad-hoc collections, distinct from the hierarchy tree.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-115",
    section: "§9",
    summary: "Every explicit process must transform at least one object.",
    stage: "verifier",
    status: "partial",
    implementedIn: "visual-render-verifier.ts → VR-015 (warning level, per-OPD scope)",
    verifierCode: "VR-015",
    note: "Per-OPD check emits warning — V-115 operates at the atlas level; a subprocess may satisfy it in a sibling OPD. Full check would iterate across the whole atlas.",
  },
  {
    code: "V-116",
    section: "§10.12",
    summary: "Semi-folding: refiners shown as triangle icons inside the whole's rectangle.",
    stage: "renderer",
    status: "implemented",
    implementedIn: "visual-render-spec-to-joint-graph.ts → isSemiFolded → semiFoldIcon embedded",
  },
  {
    code: "V-117",
    section: "§10.12",
    summary: "Semi-folding is per-refiner: some can be folded while others remain extracted.",
    stage: "spec-compiler",
    status: "deferred",
    note: "VisualRenderNode.isSemiFolded is per-node. Per-refiner granularity needs kernel support.",
  },
  {
    code: "V-118",
    section: "§10.12",
    summary: "Numeric indicator shows how many refiners remain hidden inside the semi-fold.",
    stage: "renderer",
    status: "partial",
    implementedIn: "fan-shape.ts → hiddenRefinersCount suffix '+N' in badge label; visual-render-spec-to-joint-graph.ts passes field",
    note: "Badge shows '+N'. Full per-refiner granularity requires kernel support for tracking hidden children.",
  },
  {
    code: "V-119",
    section: "§10.12",
    summary: "Semi-folding state is per-OPD (per-appearance), not per-model entity.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → isSemiFolded in VisualRenderNode (per-OPD slice)",
  },
  {
    code: "V-120",
    section: "§10.12",
    summary: "Procedural links can connect directly to semi-folded refiners inside the whole's rectangle.",
    stage: "renderer",
    status: "deferred",
    note: "Requires routing links to enter parent rectangle and point to inner refiner label.",
  },
  {
    code: "V-121",
    section: "§14.1",
    summary: "Lexical naming convention inherited from OPL layer; this visual layer adds no parallel policy.",
    stage: "not-applicable",
    status: "not-applicable",
  },
  {
    code: "V-122",
    section: "§14.1",
    summary: "Things may display a short alias next to their name (e.g. 'Turbojet Engine System (tes)').",
    stage: "renderer",
    status: "partial",
    implementedIn: "visual-render-spec-to-joint-graph.ts → displayLabel = label (alias); kernel-to-visual-render-spec.ts → alias propagation",
    note: "Alias appended as '(alias)' in display label. Rendering uses same font — no separate smaller-font alias yet.",
  },
  {
    code: "V-123",
    section: "§14.4",
    summary: "Appearance vs. existence: a thing exists once but can appear in multiple OPDs.",
    stage: "spec-compiler",
    status: "implemented",
    implementedIn: "kernel-to-visual-render-spec.ts → per-OPD slice compilation of same kernel entities",
  },
];

/** Retorna reglas con status deferred — pendientes de implementación. */
export function deferredRules(): VisualRuleEntry[] {
  return VISUAL_RULES_REGISTRY.filter((r) => r.status === "deferred");
}

/** Retorna reglas implementadas en un stage específico. */
export function rulesByStage(stage: VisualRuleStage): VisualRuleEntry[] {
  return VISUAL_RULES_REGISTRY.filter((r) => r.stage === stage);
}

/** Retorna reglas con verifier code asignado. */
export function verifierRules(): VisualRuleEntry[] {
  return VISUAL_RULES_REGISTRY.filter((r) => r.verifierCode !== undefined);
}

/** Reporte de cobertura por status. */
export function coverageReport(): Record<VisualRuleStatus, number> {
  const report: Record<VisualRuleStatus, number> = {
    implemented: 0,
    partial: 0,
    deferred: 0,
    "not-applicable": 0,
    "simulation-only": 0,
    eliminated: 0,
  };
  for (const rule of VISUAL_RULES_REGISTRY) {
    report[rule.status]++;
  }
  return report;
}
